### ISSUE TITLE
ヒアリング顧客の確保

### ISSUE THREAD

**Issue by corentytakeshi** [tokyoLunch/biz#17]
## ルール
- estimate(工数見積)とassign(担当者)を設定してください。
- estimateを変えるときは理由を記載してください。
- 調査過程などをコメントに記載してください。

## 目的
- 顧客ヒアリングを実施するにあたり、ヒアリング対象者を確保する

## ゴール
- ヒアリング対象者が確保されていること、ヒアリングに対する合意を得ていること。

## 関連するURL
- 特になし

**Comment by ritsuki-fujisaki** [comment]
estimate(工数見積)とassign(担当者)を設定してください。
準備について延べ3日(Biz, Dev, ML観点での質問内容及び進め方精査に関する準備)、実施工数として1時間*3人
Assigneeについて、メインは藤原、藤崎とする。 4名をTL側最大参加人数として都度Assigneeについては検討。
質問内容については、google drive内excel sheetを参照のこと。

**Comment by corentytakeshi** [comment]
調整済みクローズ
