### ISSUE TITLE
カスタマーインタビューの日程調整

### ISSUE THREAD

**Issue by corentytakeshi** [tokyoLunch/biz#18]
## ルール
- estimate(工数見積)とassign(担当者)を設定してください。
- estimateを変えるときは理由を記載してください。
- 調査過程などをコメントに記載してください。

## 目的
- カスタマーヒアリングの日程を決定する

## ゴール
- カスタマーヒアリングのスケジュールが確定していること
- カスタマーヒアリングの参加者が確定していること

## 関連するURL
- 参考文献や調査資料を書いてください。

**Comment by corentytakeshi** [comment]
@ritsuki-fujisaki 
こちらファシリテートおねがいー

**Comment by ritsuki-fujisaki** [comment]
第一回について3/27にて実施予定。
3月中に延べ5人行えると嬉しい。

**Comment by ritsuki-fujisaki** [comment]
Assigneeへやまけんを追加。 3月中3人調整を行うことを期待している。

**Comment by corentytakeshi** [comment]
調整済みクローズ
