### ISSUE TITLE
見込み顧客へのインタビューの実施

### ISSUE THREAD

**Issue by ritsuki-fujisaki** [tokyoLunch/biz#20]
## ルール
- estimate(工数見積)とassign(担当者)を設定してください。
- estimateを変えるときは理由を記載してください。
- 調査過程などをコメントに記載してください。

## 目的
Customer-Problem fitに関する仮説検証を行うため。
仮説内容については下記google driveを参照。

## ゴール
仮説検証が行われたこと。 (仮説の真偽は問わない。)

## 関連するURL
https://docs.google.com/spreadsheets/d/11ODO1DA6eZ1TqvKMtzSWmuB7i9F3DILlvmKNkp-CnuU/edit#gid=342794310

**Comment by ritsuki-fujisaki** [comment]
3/27にて実施予定。
対象ペルソナ及び結果については別途ドキュメンテーションを行う。

**Comment by ritsuki-fujisaki** [comment]
メインのintervier参加者については、調整担当者、橋本、大垣、藤崎を予定。
TL側最大出席者数を4名とし、適宜assignを行う。

**Comment by corentytakeshi** [comment]
https://drive.google.com/drive/u/0/folders/1aIGmZBC1EbiEj6WEjB4DIdKG9O50Dpx8
実施済み。
メモは☝️に記載
クローズ
